// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-cvs.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_cvs_default = defineTool({
  name: "list_cvs",
  title: "List CVs",
  description: "List the signed-in user's CVs (id, title, language, updated_at). Includes the base profile and any tailored applications.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Maximum number of CVs to return. Defaults to 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("resumes").select("id, title, language, updated_at, created_at").order("updated_at", { ascending: false }).limit(limit ?? 50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { cvs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-cv.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_cv_default = defineTool2({
  name: "get_cv",
  title: "Get CV",
  description: "Fetch the full content of one of the signed-in user's CVs by id, including profile, experience, education, skills, and metadata.",
  inputSchema: {
    id: z2.string().uuid().describe("The CV id (from list_cvs).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("resumes").select("id, title, language, template_id, updated_at, created_at, content_json").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "CV not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { cv: data }
    };
  }
});

// src/lib/mcp/tools/list-job-postings.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_job_postings_default = defineTool3({
  name: "list_job_postings",
  title: "List job postings",
  description: "List job postings the signed-in user has saved for CV tailoring.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).optional().describe("Maximum number of postings to return. Defaults to 25.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("job_postings").select("id, job_title, company_name, seniority_level, industry, detected_language, created_at").order("created_at", { ascending: false }).limit(limit ?? 25);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { postings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-bullet-bank.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_bullet_bank_default = defineTool4({
  name: "list_bullet_bank",
  title: "List saved bullets",
  description: "List the signed-in user's saved bullet-point library, optionally filtered by tag.",
  inputSchema: {
    tag: z4.string().optional().describe("Filter by tag substring."),
    limit: z4.number().int().min(1).max(200).optional().describe("Maximum bullets to return. Defaults to 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tag, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let q = supabaseForUser4(ctx).from("bullet_bank").select("id, text, tags, created_at").order("created_at", { ascending: false }).limit(limit ?? 50);
    if (tag) q = q.contains("tags", [tag]);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { bullets: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "suokeaxtmhgakgtgcdwc";
var mcp_default = defineMcp({
  name: "cvsakert-mcp",
  title: "CVS\xE4kert",
  version: "0.1.0",
  instructions: "Tools for CVS\xE4kert. Read the signed-in user's CVs, tailored applications, saved job postings, and bullet library. All reads are scoped to the user by RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_cvs_default, get_cv_default, list_job_postings_default, list_bullet_bank_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
